name: Semgrep Security Scan

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Security Repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Clone Target Repositories
        run: |
          gh repo clone Ayushsaini20/100-Days-Of-Code
          gh repo clone Ayushsaini20/Pair_trading_in_cryptocurrency
          gh repo clone Ayushsaini20/HelmChart_hpa

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep on Repos
        run: |
          semgrep scan --config=auto repo1/
          semgrep scan --config=auto repo2/
          semgrep scan --config=auto repo3/

      - name: Upload Semgrep Results
        run: |
          mkdir -p reports
          semgrep scan --config=auto repo1/ --json > reports/repo1.json
          semgrep scan --config=auto repo2/ --json > reports/repo2.json
          semgrep scan --config=auto repo3/ --json > reports/repo3.json
        continue-on-error: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-reports
          path: reports/
